### ISSUE TITLE
Synchronized order book using level2 channel

### ISSUE THREAD

**Issue by gabrieldodan** [coinbase/coinbase-pro-node#183] opened 2017-12-29 15:42 UTC
Hi, I am trying to create a synchronized order book using level2 channel but it doesn't works proper. After a while the order book become de-synchronized , the spread is negative. What I am doing is to subscribe to level2 channel, take the snapshot sent via websocket then apply the changes from l2update messages type. I am using  version 0.5.0 of the module.

Any idea? Has someone successfully managed to keep a synchronized order book using level2 channel?

Thanks!

**Comment by rmm5t** [comment] 2017-12-29 16:04
@gabrieldodan Are you ensuring that the `WebsocketClient` stays connected via the data in the `heartbeat` channel? 

When a disconnect or data loss is recognized, it is likely necessary to recapture the full level2 order book snapshot to force a re-sync while reconnecting the websocket.

For more information see:

* #82 
* https://github.com/coinbase/gdax-node/commit/94c671c8f784bd6fff5d5c8203cec52c72c0199f#r26523575
* https://github.com/coinbase/gdax-node/issues/148#issuecomment-351431901

I personally have a goal to make the WebsocketClient more resilient while also emitting an event when a disconnect is recognized. You could then use that to resync your orderbook.

Of course, if the above is combined with #82, in theory, we could automate all of this with a rewritten `OrderbookSync`.

**Comment by gabrieldodan** [comment] 2018-01-03 13:47
@rmm5t there is no disconnection from WebsocketClient . Also there is no discontinuity of trade_id , I mean always current trade_id = previous trade_id + 1

**Comment by rmm5t** [comment] 2018-01-03 15:51
> Also there is no discontinuity of trade_id

:thinking: I'm a little confused.  The `level2` websocket channel doesn't provide a `trade_id` in its payloads.  The `matches` channel would have sequential `trade_id` values, but how does that channel apply to your Level 2 Orderbook?

>  I mean always current trade_id = previous trade_id + 1

Just confirming. Do you have an assertion in place to guarantee this?

**Comment by gabrieldodan** [comment] 2018-01-03 16:54
Hi sorry for confusion. You told me to ensure there is no disconnection or data loss. How can I detect data loss? I know that  ``matches``  messages does not affect level2 order book. But I don't know how I could detect data loss because l2update messages have no sequence number . so I supposed I could detect data losses using trade_Id of the matches messages

**Comment by rmm5t** [comment] 2018-01-03 17:33
Understood. Valid points. The `heartbeat` channel is intended to be used for recognizing this kind of data loss, but I suppose even that doesn't necessarily guarantee anything with regards sub-second `level2` channel hiccups --effectively what you're claiming.

How frequently are you seeing your Level 2 orderbook go out of sync? Is is easily reproducible? If so, I might try to reproduce your same problem later this week (or month). That might be a good start towards rewriting the `OrderbookSync` too (see #82).

**Comment by gabrieldodan** [comment] 2018-01-03 18:08
It is easily reproducible. Hope to have time tomorrow to create a small script that reproduce the issue and will post here.

I have noticed that gdax.com use a ``level2_50`` channel but that channel is not documented. Anyway I have tried with that channel and same issue.

**Comment by rmm5t** [comment] 2018-01-03 18:40
> I have noticed that gdax.com use a level2_50 channel but that channel is not documented. Anyway I have tried with that channel and same issue.

My main critique of this issue thread so far is that gdax.com doesn't have the same synchronization issues that you're claiming (they use the exact same API endpoints). Are you sure this isn't an issue with your client's implementation?

**Comment by gabrieldodan** [comment] 2018-01-04 11:26
I am not excluding a potential error on my code, that's why I have asked if someone managed to keep a synchronized order book using level2 channel.

I have created a script that reproduce the issue. See below, please install gdax module first ``npm install coinbase/gdax-node`` . Take a look please and let me know if the issue happens for you also or you see any error on my code. Thanks!

```
var Gdax = require('gdax');

var orderBook = {
    bids: {},
    asks: {}
};


var wsGdax = new Gdax.WebsocketClient(
    ['BTC-EUR'], 
    'wss://ws-feed.gdax.com',
    null,
    {channels: ['level2', 'heartbeat']}
);

wsGdax.on('message', function(data) {

    if(data.type === 'snapshot') {
        // save snapshot on orderBook object
        for(var i=0; i<data.bids.length; i++) {
            var bid = data.bids[i];
            orderBook.bids[bid[0]] = bid[1];
        }
        for(var i=0; i<data.asks.length; i++) {
            var ask = data.asks[i];
            orderBook.asks[ask[0]] = ask[1];
        }
        return;
    }

    if(data.type === 'l2update') {
        // apply the changes
        var changes = data.changes;
        for(var i=0; i<changes.length; i++) {
            var change = changes[i];
            if(change[0] === 'buy') {
                if(change[2] === '0') {
                    delete orderBook.bids[change[1]];
                } else {
                    orderBook.bids[change[1]] = change[2];
                }
            } else if (change[0] === 'sell') {
                if(change[2] === '0') {
                    delete orderBook.asks[change[1]];
                } else {
                    orderBook.asks[change[1]] = change[2];
                }
            }
        }
        
        // crate arrays then sort
        var bids = [];
        var asks = [];
        for(var price in orderBook.bids) {
            bids.push([parseFloat(price), parseFloat(orderBook.bids[price])]);
        }
        for(var price in orderBook.asks) {
            asks.push([parseFloat(price), parseFloat(orderBook.asks[price])]);
        }
        
        // sort asc
        asks.sort(function (a, b) {
            return a[0] - b[0];
        });

        // sort desc
        bids.sort(function (a, b) {
            return b[0] - a[0];
        });
        
        if( asks[0][0] < bids[0][0] ) {
            console.log('order book out of sync', asks[0], bids[0]);
        }
        return;
    }
});

wsGdax.on('close', function(data) {
    console.log('wsGdax closed:', data);
});

wsGdax.on('error', function(data) {
    console.log('wsGdax error:', data);
});

wsGdax.on('open', function() {
    console.log('wsGdax opened');
});

```

**Comment by gabrieldodan** [comment] 2018-01-12 08:27
Hi @rmm5t have you had time to test the above code? Thanks!

**Comment by rmm5t** [comment] 2018-01-12 15:04
> Hi @rmm5t have you had time to test the above code? Thanks!

Sorry. No, not yet. Client work got the best of me, but thanks for the nudge. I would have forgotten otherwise.

**Comment by alexukr** [comment] 2018-01-20 07:05
Regarding discontinuity of the messages: as I understand, for level2 one can check for sequence numbers. E.g.: https://github.com/danpaquin/gdax-python/blob/master/gdax/order_book.py#L70 - here they reset order book every time they detect that the new sequence is not equal previous sequence plus one.
Did you try that? How often would you detect sequence gap for your level2 order book implementation?

**Comment by alexukr** [comment] 2018-01-20 07:25
I'm sorry for the confusion, l2update messages do not have "sequence" field. And actually GDAX API documentation states that level2 "guarantees delivery of all updates". So it's strange it goes out of sync with what their web-ui shows. Are you sure they use level2 for it? Maybe they maintain level3 (or full) channel for their web-ui which works properly and not level2?

**Comment by fb55** [comment] 2018-01-20 12:18
The website essentially uses the level 2 channel. `level2_50` is an undocumented variant that buffers messages for 50ms and sends combined updates, which helps with site performance when there is a lot of action — the underlying datasource is still the same.

The syncing logic can be a bit tricky, and while I can't spot the error in @gabrieldodan's code, I will put adding an implementation to this repo on my todo list.

**Comment by alexukr** [comment] 2018-01-20 15:20
I actually also observe out of sync for my implementation like if some l2update messages which should remove old best bid or ask are missing so they stick forever.
I tried to switch to level2_50 and the same algorithm showed much more stable bahaviour: the numbers were exactly the same as on the website and updates were not delayed (for level2 I often notice that sometimes there is no incoming messages for some time and then they resume). Only once for a brief moment I saw out of sync with level2_50 but it quickly recovered by itself (without restarting the feed).

Also, do you know if "buy" and "sell" in level2 update message always correspond to bids and asks respectively? I also suspect that sometimes level2 updates that should erase best bid may come as "sell", not as "buy", and maybe this is why I skip it and go out of sync?

**Comment by fb55** [comment] 2018-01-20 16:14
> do you know if "buy" and "sell" in level2 update message always correspond to bids and asks respectively

They do. If a price level moves sides, you should see a message from the original side with size `0` first, then a second one adding it to the other side.

Thinking about it, for the snipped above, the hardcoded `'0'` could potentially be an issue as the value is expected to be parsed with eg. `big.js`.

**Comment by rmm5t** [comment] 2018-01-20 22:14
@gabrieldodan I tried your code snippet. I was able to reproduce the same `out of sync` errors, but the underlying code is suspect.

1. The code is pretty inefficient. You should consider a [Red-Black Search Tree](https://github.com/vadimg/js_bintrees) instead of keeping the orderbook in an object (with string keys) and then rewriting those to arrays (with floats) for sorting.
2. You should **_never_** _ever_ rely on `parseFloat` (or floats in general) for financials (especially in JavaScript and especially for high precision numbers). Use [bignumber.js](https://github.com/MikeMcl/bignumber.js) or [big.js](https://github.com/MikeMcl/big.js) (as @fb55 alluded).  Otherwise,  you will very likely have a really bad day:
    ```bash
    $ node

    > parseFloat('10640.00000001') - parseFloat('10640.00000000')
    1.0000803740695119e-8 # Close, but not exactly.

    > 111111111000000000 + 333
    111111111000000340 # Brilliant. 😠

    > 111111111000000000 * 10000 % 10000
    5424 # Well, that's less than useful
    ```
3. Relying on the string values in one snippet and the numeric values in another is asking for trouble
 (also as @fb55 alluded about `'0'`).

**Comment by dalikman** [comment] 2018-02-05 01:45
Hi,

I'm also seeing sync issues.  I'm pushing big-js values into a red-black tree using the 'message' event.

My suspicion is that messages are being silently dropped during high load.  The websocket connection appears stable though, and I can see heartbeats continue to flow.

The reason I suspect dropped messages is because I am monitoring top of one side of the book and comparing to the web client.  When the price moves away from top of book (ie, the best ask price moves higher), my application "sticks" at the old price.  When the price moves back down and passes the price I am stuck at, I'm back in sync (from a top of book view anyway).  So not receiving/processing the l2update message setting the top of book price to 0 would explain this behaviour.   Hope that makes sense?

I see the same behaviour with both the l2update and l2update_50 channels.  Also seeing this on my WIndows 10 dev PC and an unbuntu 16_04 server I have hosted in a data centre.  Neither show any obvious signs of resource contention.  This is a dedicated gdax feed handler I am writing so literally nothing else is happening other than processing the initial snapshot and the subsequent l2updates.

Does anyone have any suggestions as to how I could try and narrow down the source of the issue?

I guess I could run a packet capture and make sure the updates are actually hitting the machine, but off the top of my head not sure how I could decrypt the wss payload.

Appreciate any suggestions/help!

Thanks

**Comment by alexukr** [comment] 2018-02-05 03:17
I had the same issue - "dropped" l2update messages. For me the cause of the problem was in my websocket parsing code (I was implementing websocket connection myself in C++): it turned out the GDAX server can (and often does) send multiple websocket frames (containing multiple messages, e.g. l2update) in a single packet. So when I was reading data from the socket, in just a single recv I received a buffer containing 2-3 websocket frames. I parsed only the first frame, and right away called another recv, so effectively I dropped the remaining messages in the buffer from the previous recv.
Maybe your websocket parsing code has the same issue.

**Comment by dalikman** [comment] 2018-02-05 09:26
Thanks, I will certainly look into this.  I am using the gdax node implementation (ie, this repo) and so haven't directly setup the websocket connection.  My code handles for multiple updates in a single message though (ie, multiple arrays in the "changes" field), which I know isn't the same as what you are saying, so I will definitely see if this is happening.

Thanks again for the heads up!

**Comment by dalikman** [comment] 2018-02-05 11:41
OK, looks like it is the rbtree implementation I am using.  I am catching conditions where it should delete an order from the tree, but its not.  whats bugging me is that sometimes it does, sometimes it doesn't, so need to work out why....

**Comment by t2048** [comment] 2018-02-08 07:32
Just want to chime in and say I also today tried to get an 'l2update' order book to work but failed. It would get out of sync very quickly. As far as I see in this thread, everyone who has tried has had similar failures. I've moved on and am using the reference 'full' order book code but I do think this issue is still not resolved.

**Comment by adityamertia** [comment] 2018-02-11 09:07
@dalikman which rbtree implementation did you use. Gdax uses @https://github.com/vadimg/js_bintrees If this is giving the issue in deleting the order, did you try any other rbtree impl. I am curious to see if this resolves the issue, as i am facing same issue. Let me know if you already found a solution to the problem?

**Comment by eazy** [comment] 2018-03-24 00:25
@gabrieldodan were you able to fix your code?

I have nearly the same implemenation in php running and I'm trying to port that script to nodejs to get it a bit faster.

I think the main problem is the time that you need to sort your arrays, if you will do that with binarysearch it should be good enough to get all frames from the socket. I had the same problem with my php code.

**Comment by silahian** [comment] 2018-04-28 10:47
Same on you GDAX!
We nearly spend more than a month looking for this websocket issue... level2 update just don't work
Thanks to this thread we found the undocumented l2update_50 which works.
Even though is not the perfect solution, because the delay they use with l2update_50 and having just the top-50 levels, I hope others can also find this thread and don't waite their time.

I just can't believe GDAX still is a company.

**Comment by alexukr** [comment] 2018-04-28 14:51
I think if there really was a bug at GDAX side there would be much more people complaining about it in threads like this and GDAX would have noticed and fixed that already.
As I said I also had the same issue with similar symptoms and it looked to me I was doing everything right and GDAX just dropped some packets, I didn't see any other reasons. But then eventually I found a bug in my code and fixed that. Now both "level2" and "full" channels work for me correctly and since then I've never seen that their web UI showed different values in the order book or trades from what I had in my program (and I tested it on my program running for few days with no restarts).

**Comment by vgoklani** [comment] 2018-07-10 11:31
We had a similar issue. Unfortunately it appears that GDAX/Coinbase periodically bounce the level2 feed. The solution was to reset the orderbook after each bounce. We subscribe to both the "level2" and the "heartbeat" channel, so it's unclear why the websocket connections break.

**Comment by fb55** [comment] 2018-08-16 11:55
> Even though is not the perfect solution, because the delay they use with l2update_50 and having just the top-50 levels, I hope others can also find this thread and don't waste their time.

`l2update_50` is emitted every 50ms. It is not limited to a specific number of price levels. It is intended to be used when displaying values to humans, as latency doesn't matter there and it is easier to see changes happen.

This channel just aggregates the `l2update` (it literally subscribes to it). If you're able to subscribe to the aggregated channel it would be very odd if the original does not work.

**Comment by adityamertia** [comment] 2018-08-16 14:53
@fb55 Any update on when the orderbook(gdax-node) will officially support level2?

**Comment by drewrothstein** [comment] 2020-01-16 05:44
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed by drewrothstein** 2020-01-16 05:44 UTC
